# docker-compose up --remove-orphans --force-recreate
version: '3'

services:
  app:
    image: zao111222333/spinalhdl-online
    container_name: spinalhdl-online
    restart: always
    environment:
      - USER=username
      - PASSWORD=123456
      - WORKDIR=/SpinalHDL
      - GDK_MAX_PORT=2
    volumes:
      - ~/SpinalHDL-Share:/SpinalHDL
      - ~/KEY:/KEY
    ports:
      - 8848:8080
      - 2222:22